### 
POST http://localhost:4000/user/login
Authorization: Basic QWRtaW46YmVzdFBhc3N3b3JkRXZlcg==

###
GET http://localhost:4000/post/get

###

GET http://localhost:4000/post/get/61df4f83360b20298da3fad7

###
POST http://localhost:4000/post/create
Content-Type: application/json

{
    "title": "TestPostYOYddddO",
    "content": "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.",
    "categories": ["61ae49a754ec37e3d0acc031"],
    "post_image": "https://www.hotel-nuovaitalia.com/images/home-banner-1.jpg"
}


###
PUT http://localhost:4000/post/update/61df4b6ff250775ee5d9363c
Content-Type: application/json

{
    "title": "TestPost",
    "content": "Content of Testpost",
    "post_image": "https://www.hotel-nuovaitalia.com/images/home-banner-1.jpg",
    "categories": ["61ae49a754ec37e3d0acc033"]
}
###
PUT http://localhost:4000/post/update/61df4b6af250775ee5d93637
Content-Type: application/json

{
    "post_image": "https://www.hotel-nuovaitalia.com/images/home-banner-1.jpg"
}

###
GET http://localhost:4000/post/get/61b22cdb2c20172ab919f4c4


###
DELETE http://localhost:4000/post/delete/61df4b04f78eda6cf796e958

###
POST http://localhost:4000/file/upload/61b2374dc8fdfa72d661bcbf
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="text"

title
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="post_image"; filename="test.png"
Content-Type: image/png

< ./default_profile_image.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--
