### 
POST http://localhost:4000/user/login
Authorization: Basic QWRtaW46YmVzdFBhc3N3b3JkRXZlcg==

### 
POST http://localhost:4000/user/logout


### 
PUT http://localhost:4000/user/changePassword
content-type: application/json

{
    "oldPassword": "bestPasswordEver",
    "newPassword": "whatever"
}

### 
PUT http://localhost:3000/user/changePassword
content-type: application/json

{
    "oldPassword": "whatever",
    "newPassword": "bestPasswordEver"
}