//DIALOGS
export const SHOW_LOGIN_DIALOG = 'SHOW_LOGIN_DIALOG';
export const HIDE_LOGIN_DIALOG = 'HIDE_LOGIN_DIALOG';

//AUTHENTICATION / LOGIN
export const AUTHENTICATION_SUCCESS = 'AUTHENTICATION_SUCCESS';
export const AUTHENTICATION_ERROR = 'AUTHENTICATION_ERROR';
export const AUTHENTICATION_PENDING = "AUTHENTICATION_PENDING";

//LOGOUT
export const LOGOUT_USER = "LOGOUT_USER";
