//LOGIN
export const SHOW_LOGIN_DIALOG = 'SHOW_LOGIN_DIALOG';
export const HIDE_LOGIN_DIALOG = 'HIDE_LOGIN_DIALOG';

//AUTHENTICATION
export const AUTHENTICATION_SUCCESS = 'AUTHENTICATION_SUCCESS';
export const AUTHENTICATION_ERROR = 'AUTHENTICATION_ERROR';
export const AUTHENTICATION_PENDING = "AUTHENTICATION_PENDING";

export const LOGOUT_USER = "LOGOUT_USER";

//USER LIST
export const ALLUSERS_SUCCESS = 'ALLUSERS_SUCCESS'
export const ALLUSERS_ERROR = 'ALLUSERS_ERROR'
export const USER_PENDING = 'USER_PENDING'

//EDIT USER
export const EDIT_SUCCESS = 'EDIT_SUCCESS'
export const EDIT_ERROR = 'EDIT_ERROR'
export const SHOW_EDIT_DIALOG = 'SHOW_EDIT_DIALOG';

export const HIDE_DIALOG = 'HIDE_DIALOG'

